spring:
  application:
    name: jdgolf
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://localhost:3306/jdgolf
    url: jdbc:h2:mem:testJDGOLF?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 991911
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 9000
  servlet:
    session:
      tracking-modes: cookie